INSERT INTO contact (EMAIL,FIRSTNAME,LASTNAME,TELEPHONE) VALUES ('email1@email.com','Jhon','Anderson','60650654');
INSERT INTO contact (EMAIL,FIRSTNAME,LASTNAME,TELEPHONE) VALUES ('email1@email2.com','Jhon2','Anderson','60650654');
INSERT INTO contact (EMAIL,FIRSTNAME,LASTNAME,TELEPHONE) VALUES ('email1@email3.com','diana','haston','60650654');
INSERT INTO contact (EMAIL,FIRSTNAME,LASTNAME,TELEPHONE) VALUES ('email1@email4.com','Robinsson','Relfech','60650654');
